services:
  web:
    image: client-portal-next:latest
    build:
      context: ./next
      dockerfile: Dockerfile.next
    ports:
      - "8007:3000"
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:8007}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/client_portal?schema=public}
      # Optional seed vars (admin initial). Leave empty to skip or set via .env.prod
      - SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL}
      - SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD}
      - SEED_ADMIN_NAME=${SEED_ADMIN_NAME}
    restart: unless-stopped
    volumes:
      - storage:/app/storage
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=client_portal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  storage:
  pg_data:
