services:
  web:
    image: node:20
    working_dir: /app
    volumes:
      - ./next:/app
      - /app/node_modules
    ports:
      - "8007:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:8007
      - NEXTAUTH_SECRET=devsecret
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/client_portal?schema=public
    command: sh -lc "npm i --silent && npx prisma generate && npm run dev"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=client_portal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
