services:
  app:
    image: client-portal:latest
    build:
      context: ./nuxt
      dockerfile: Dockerfile.nuxt
    expose:
      - "3000"
    restart: unless-stopped
  caddy:
    image: caddy:2-alpine
    depends_on:
      - app
    ports:
      - "8007:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped
