services:
  web:
    image: client-portal-next:latest
    build:
      context: ./next
      dockerfile: Dockerfile.next
    ports:
      - "8007:3000"
    env_file:
      - .env.prod
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:8007}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    restart: unless-stopped
